"""Generate AI-reader output files alongside every pipeline run.

Produces four files that make generated documentation discoverable
and consumable by LLMs, coding agents, and AI assistants:

* ``llms.txt``      — Curated index following the llmstxt.org spec.
* ``llms-full.txt`` — All generated content concatenated into one file.
* ``AGENTS.md``     — Cross-agent coding instructions (Codex, Devin, …).
* ``CLAUDE.md``     — Claude Code specific context file.
"""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from typing import TYPE_CHECKING

from ..core.models import GenerationResult, OutputFormat

if TYPE_CHECKING:
    from ..core.template_vars import TemplateVars

# ---------------------------------------------------------------------------
# Human-readable labels & one-line descriptions for each output format
# ---------------------------------------------------------------------------

_FORMAT_META: dict[OutputFormat, tuple[str, str]] = {
    OutputFormat.WORD: ("Word Document", "Full documentation exported as .docx"),
    OutputFormat.PDF: ("PDF Document", "Printable documentation in PDF format"),
    OutputFormat.PPTX: ("PowerPoint Slides", "Slide deck summarising the project"),
    OutputFormat.BLOG: ("Blog Post", "SEO-friendly Markdown blog post"),
    OutputFormat.JIRA: ("Jira Tickets", "Structured Jira-ready issue descriptions"),
    OutputFormat.CHANGELOG: ("Changelog", "Auto-generated changelog from the README"),
    OutputFormat.LATEX: ("LaTeX Document", "Academic-style LaTeX source"),
    OutputFormat.ONEPAGER: ("One-Pager", "Single-page executive summary"),
    OutputFormat.SOCIAL: ("Social Posts", "Ready-to-publish social media snippets"),
    OutputFormat.FAQ: ("FAQ", "Frequently-asked-questions document"),
    OutputFormat.ARCHITECTURE: ("Architecture Diagram", "Mermaid architecture overview"),
    OutputFormat.MINDMAP: ("Mindmap", "Mermaid mindmap of the project structure"),
}

# File extensions that can be inlined as plain text
_INLINEABLE_EXTS = frozenset({".md", ".tex", ".txt", ".mmd", ".mermaid", ".json", ".csv"})


class AIReadersGenerator:
    """Generate AI-reader companion files from pipeline outputs.

    This generator is **not** a regular ``BaseGenerator`` subclass — it
    runs *after* all format generators have finished and operates on
    the collected ``GenerationResult`` list rather than the
    ``DocumentModel`` directly.
    """

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def generate_llms_txt(
        self,
        results: list[GenerationResult],
        project_name: str,
        description: str,
        output_dir: Path,
    ) -> Path:
        """Create ``llms.txt`` following the `llmstxt.org <https://llmstxt.org>`_ spec.

        Parameters
        ----------
        results
            List of ``GenerationResult`` objects from the pipeline run.
        project_name
            Human-readable project name used as the document title.
        description
            One-line project description (falls back to a generic blurb).
        output_dir
            Directory where ``llms.txt`` will be written.

        Returns
        -------
        Path
            Absolute path to the generated ``llms.txt``.
        """
        lines: list[str] = []

        # Title line
        lines.append(f"# {project_name}")
        lines.append("")

        # Description block
        desc = description or f"Documentation generated by OpenDocs for {project_name}."
        lines.append(f"> {desc}")
        lines.append("")

        # Documentation section — list successful outputs
        successful = [r for r in results if r.success]
        if successful:
            lines.append("## Documentation")
            lines.append("")
            for r in successful:
                label, one_liner = _FORMAT_META.get(
                    r.format,
                    (r.format.value.title(), f"{r.format.value.title()} output"),
                )
                lines.append(f"- [{label}]({r.output_path.name}): {one_liner}")
            lines.append("")

        # Optional section — reference to the full dump
        lines.append("## Optional")
        lines.append("")
        lines.append("- [Full Documentation](llms-full.txt): All documentation in one file")
        lines.append("")

        out = output_dir / "llms.txt"
        out.write_text("\n".join(lines), encoding="utf-8")
        return out

    # ------------------------------------------------------------------

    def generate_llms_full_txt(
        self,
        results: list[GenerationResult],
        output_dir: Path,
    ) -> Path:
        """Concatenate all generated outputs into ``llms-full.txt``.

        Text-based formats (``.md``, ``.tex``, ``.txt``, …) are inlined;
        binary formats (``.docx``, ``.pdf``, ``.pptx``) are referenced
        by filename.

        Parameters
        ----------
        results
            List of ``GenerationResult`` objects from the pipeline run.
        output_dir
            Directory where ``llms-full.txt`` will be written.

        Returns
        -------
        Path
            Absolute path to the generated ``llms-full.txt``.
        """
        parts: list[str] = []

        successful = [r for r in results if r.success]
        for r in successful:
            label, _ = _FORMAT_META.get(
                r.format,
                (r.format.value.title(), ""),
            )
            header = f"{'=' * 60}\n{label} ({r.output_path.name})\n{'=' * 60}"

            if r.output_path.suffix.lower() in _INLINEABLE_EXTS:
                try:
                    content = r.output_path.read_text(encoding="utf-8")
                except Exception:
                    content = f"[Could not read {r.output_path.name}]"
                parts.append(f"{header}\n\n{content}")
            else:
                parts.append(f"{header}\n\n[Binary file — see {r.output_path.name}]")

        out = output_dir / "llms-full.txt"
        out.write_text("\n\n".join(parts) + "\n", encoding="utf-8")
        return out

    # ------------------------------------------------------------------

    def generate_agents_md(
        self,
        project_name: str,
        template_vars: TemplateVars | None,
        output_dir: Path,
        results: list[GenerationResult] | None = None,
    ) -> Path:
        """Create ``AGENTS.md`` — cross-agent coding instructions.

        Parameters
        ----------
        project_name
            Human-readable project name.
        template_vars
            Optional ``TemplateVars`` with author/version/org metadata.
        output_dir
            Directory where ``AGENTS.md`` will be written.
        results
            Optional list of ``GenerationResult`` for listing available docs.

        Returns
        -------
        Path
            Absolute path to the generated ``AGENTS.md``.
        """
        now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
        lines: list[str] = []

        lines.append(f"# AGENTS.md — {project_name}")
        lines.append("")
        lines.append("This file provides context for AI coding agents ")
        lines.append("(Codex, Devin, Copilot Workspace, etc.) working in this repository.")
        lines.append("")

        # Project info
        lines.append("## Project Info")
        lines.append("")
        lines.append(f"- **Name:** {project_name}")
        if template_vars:
            if template_vars.version:
                lines.append(f"- **Version:** {template_vars.version}")
            if template_vars.author:
                lines.append(f"- **Author:** {template_vars.author}")
            if template_vars.organisation:
                lines.append(f"- **Organisation:** {template_vars.organisation}")
            if template_vars.department:
                lines.append(f"- **Department:** {template_vars.department}")
        lines.append("")

        # Documentation available
        if results:
            successful = [r for r in results if r.success]
            if successful:
                lines.append("## Documentation Available")
                lines.append("")
                for r in successful:
                    label, desc = _FORMAT_META.get(
                        r.format,
                        (r.format.value.title(), f"{r.format.value.title()} output"),
                    )
                    lines.append(f"- **{label}** (`{r.output_path.name}`): {desc}")
                lines.append("")

        # Key files
        lines.append("## Key Files")
        lines.append("")
        lines.append("- `llms.txt` — AI-readable documentation index (llmstxt.org spec)")
        lines.append("- `llms-full.txt` — All documentation concatenated into one file")
        lines.append("- `CLAUDE.md` — Claude Code specific context")
        lines.append("")

        # Notes
        lines.append("## Notes")
        lines.append("")
        lines.append(f"- Generated by [OpenDocs](https://pypi.org/project/opendocs/) on {now}")
        lines.append("- Re-run the pipeline to refresh these files after source changes")
        lines.append("")

        out = output_dir / "AGENTS.md"
        out.write_text("\n".join(lines), encoding="utf-8")
        return out

    # ------------------------------------------------------------------

    def generate_claude_md(
        self,
        project_name: str,
        template_vars: TemplateVars | None,
        output_dir: Path,
        results: list[GenerationResult] | None = None,
    ) -> Path:
        """Create ``CLAUDE.md`` — Claude Code specific context file.

        Mirrors ``AGENTS.md`` but adds a *For Claude* section pointing
        to ``llms-full.txt``, any Mermaid diagram files, and the
        original source input.

        Parameters
        ----------
        project_name
            Human-readable project name.
        template_vars
            Optional ``TemplateVars`` with author/version/org metadata.
        output_dir
            Directory where ``CLAUDE.md`` will be written.
        results
            Optional list of ``GenerationResult`` for listing available docs.

        Returns
        -------
        Path
            Absolute path to the generated ``CLAUDE.md``.
        """
        now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
        lines: list[str] = []

        lines.append(f"# CLAUDE.md — {project_name}")
        lines.append("")
        lines.append("This file provides context for Claude Code working in this repository.")
        lines.append("")

        # Project info
        lines.append("## Project Info")
        lines.append("")
        lines.append(f"- **Name:** {project_name}")
        if template_vars:
            if template_vars.version:
                lines.append(f"- **Version:** {template_vars.version}")
            if template_vars.author:
                lines.append(f"- **Author:** {template_vars.author}")
            if template_vars.organisation:
                lines.append(f"- **Organisation:** {template_vars.organisation}")
            if template_vars.department:
                lines.append(f"- **Department:** {template_vars.department}")
        lines.append("")

        # Documentation available
        if results:
            successful = [r for r in results if r.success]
            if successful:
                lines.append("## Documentation Available")
                lines.append("")
                for r in successful:
                    label, desc = _FORMAT_META.get(
                        r.format,
                        (r.format.value.title(), f"{r.format.value.title()} output"),
                    )
                    lines.append(f"- **{label}** (`{r.output_path.name}`): {desc}")
                lines.append("")

        # For Claude section
        lines.append("## For Claude")
        lines.append("")
        lines.append("When working with this project's documentation, prefer these resources:")
        lines.append("")
        lines.append("1. **`llms-full.txt`** — Complete documentation dump; read this for full project context.")
        lines.append("2. **`llms.txt`** — Quick index of all generated files.")

        # List any Mermaid files
        mermaid_files: list[str] = []
        if results:
            for r in results:
                if r.success and r.output_path.suffix.lower() in {".mmd", ".mermaid"}:
                    mermaid_files.append(r.output_path.name)
        # Also check for a diagrams/ subdirectory
        diagrams_dir = output_dir / "diagrams"
        if diagrams_dir.is_dir():
            for p in sorted(diagrams_dir.glob("*.mmd")):
                mermaid_files.append(f"diagrams/{p.name}")

        if mermaid_files:
            lines.append("3. **Mermaid diagrams** — Visual architecture & mindmaps:")
            for mf in mermaid_files:
                lines.append(f"   - `{mf}`")

        lines.append("")

        # Notes
        lines.append("## Notes")
        lines.append("")
        lines.append(f"- Generated by [OpenDocs](https://pypi.org/project/opendocs/) on {now}")
        lines.append("- Re-run the pipeline to refresh these files after source changes")
        lines.append("")

        out = output_dir / "CLAUDE.md"
        out.write_text("\n".join(lines), encoding="utf-8")
        return out
