"""Export the knowledge graph as a Wikipedia-style wiki.

Produces a folder of inter-linked Markdown articles -- one per
community -- plus a navigable ``index.md`` landing page.  Inspired
by Graphify's ``--wiki`` flag.
"""

from __future__ import annotations

import shutil
from datetime import datetime
from pathlib import Path

from ..core.knowledge_graph import KnowledgeGraph
from ..core.models import DocumentModel, GenerationResult, OutputFormat


def generate_wiki(
    doc: DocumentModel,
    kg: KnowledgeGraph,
    output_dir: Path,
) -> GenerationResult:
    """Write a wiki folder to *output_dir* / ``wiki/``.

    Parameters
    ----------
    doc
        Parsed document model (metadata used for the header).
    kg
        Populated knowledge graph **with communities already detected**.
    output_dir
        Root output directory.  A ``wiki/`` sub-folder will be created.

    Returns
    -------
    GenerationResult
    """
    name = doc.metadata.repo_name or "project"
    safe = "".join(c if c.isalnum() or c in "-_ " else "_" for c in name)
    safe = safe.strip().replace(" ", "_")[:80] or "project"
    wiki_dir = output_dir / f"{safe}_wiki"

    try:
        # Ensure a clean wiki directory
        if wiki_dir.exists():
            shutil.rmtree(wiki_dir)
        wiki_dir.mkdir(parents=True, exist_ok=True)

        # Ensure communities exist
        if not kg.communities:
            kg.detect_communities()

        # Generate community articles
        summaries = kg.community_summary()
        article_files: list[Path] = []
        for cs in summaries:
            article_path = _write_community_article(wiki_dir, cs, kg, doc)
            article_files.append(article_path)

        # Generate entity catalog
        _write_entity_catalog(wiki_dir, kg)

        # Generate index
        index_path = _write_index(wiki_dir, doc, kg, summaries)

        return GenerationResult(
            format=OutputFormat.FAQ,  # reuse enum for file result
            output_path=index_path,
        )
    except Exception as exc:
        return GenerationResult(
            format=OutputFormat.FAQ,
            output_path=wiki_dir / "index.md",
            success=False,
            error=str(exc),
        )


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _safe_filename(text: str) -> str:
    """Convert arbitrary text to a filesystem-safe slug."""
    slug = "".join(c if c.isalnum() or c in "-_ " else "_" for c in text)
    return slug.strip().replace(" ", "_").lower()[:60] or "unnamed"


def _write_index(
    wiki_dir: Path,
    doc: DocumentModel,
    kg: KnowledgeGraph,
    summaries: list[dict],
) -> Path:
    """Write the ``index.md`` entry-point."""
    lines: list[str] = []
    project = doc.metadata.repo_name or "Project"
    now = datetime.now().strftime("%Y-%m-%d %H:%M")

    lines.append(f"# {project} -- Knowledge Wiki")
    lines.append("")
    lines.append(f"> Auto-generated by **opendocs** on {now}")
    lines.append("")
    lines.append(
        f"This wiki contains **{len(kg.entities)} entities** across "
        f"**{len(summaries)} communities**, extracted from the project documentation."
    )
    lines.append("")

    # Overview stats
    stats = kg.extraction_stats or kg.compute_stats()
    lines.append("## Quick Stats")
    lines.append("")
    lines.append("| Metric | Value |")
    lines.append("|--------|-------|")
    lines.append(f"| Total Entities | {stats.get('total_entities', 0)} |")
    lines.append(f"| Total Relations | {stats.get('total_relations', 0)} |")
    lines.append(f"| Communities | {len(summaries)} |")
    prov = {"EXTRACTED": 0, "INFERRED": 0, "AMBIGUOUS": 0}
    for e in kg.entities:
        prov[e.provenance] = prov.get(e.provenance, 0) + 1
    lines.append(f"| Extracted | {prov['EXTRACTED']} |")
    lines.append(f"| Inferred | {prov['INFERRED']} |")
    lines.append(f"| Ambiguous | {prov['AMBIGUOUS']} |")
    lines.append("")

    # Community table of contents
    lines.append("## Communities")
    lines.append("")
    lines.append("| # | Dominant Type | Size | Internal Edges | Article |")
    lines.append("|---|--------------|------|----------------|---------|")
    for cs in sorted(summaries, key=lambda s: s["size"], reverse=True):
        fname = f"community_{cs['id']}.md"
        lines.append(
            f"| {cs['id']} | {cs['dominant_type']} | {cs['size']} | {cs['internal_edges']} | [Read](./{fname}) |"
        )
    lines.append("")

    # God nodes
    gods = kg.god_nodes(top_n=5)
    if gods:
        lines.append("## Key Entities (God Nodes)")
        lines.append("")
        lines.append("| Entity | Type | Connections |")
        lines.append("|--------|------|-------------|")
        for ent, deg in gods:
            lines.append(f"| {ent.name} | {ent.entity_type.value.replace('_', ' ').title()} | {deg} |")
        lines.append("")

    # Suggested questions
    questions = kg.suggested_questions(top_n=5)
    if questions:
        lines.append("## Suggested Questions")
        lines.append("")
        for i, q in enumerate(questions, 1):
            lines.append(f"{i}. {q}")
        lines.append("")

    # Footer links
    lines.append("---")
    lines.append("")
    lines.append("[Entity Catalog](./entity_catalog.md)")
    lines.append("")

    path = wiki_dir / "index.md"
    path.write_text("\n".join(lines), encoding="utf-8")
    return path


def _write_community_article(
    wiki_dir: Path,
    cs: dict,
    kg: KnowledgeGraph,
    doc: DocumentModel,
) -> Path:
    """Write a single community article."""
    cid = cs["id"]
    members = kg.community_members(cid)
    lines: list[str] = []

    lines.append(f"# Community {cid}: {cs['dominant_type']}-Dominated Cluster")
    lines.append("")
    lines.append(
        f"This community contains **{cs['size']} entities** with "
        f"**{cs['internal_edges']} internal edges**.  The dominant "
        f"entity type is **{cs['dominant_type']}**."
    )
    lines.append("")

    # Member table
    lines.append("## Members")
    lines.append("")
    lines.append("| Entity | Type | Provenance | Confidence |")
    lines.append("|--------|------|-----------|------------|")
    for e in sorted(members, key=lambda m: m.confidence, reverse=True):
        etype = e.entity_type.value.replace("_", " ").title()
        lines.append(f"| {e.name} | {etype} | {e.provenance} | {e.confidence:.0%} |")
    lines.append("")

    # Internal relations
    member_ids = {e.id for e in members}
    internal_rels = [r for r in kg.relations if r.source_id in member_ids and r.target_id in member_ids]
    if internal_rels:
        lines.append("## Internal Relations")
        lines.append("")
        lines.append("| Source | Relation | Target |")
        lines.append("|--------|----------|--------|")
        for r in internal_rels:
            src = kg.get_entity(r.source_id)
            tgt = kg.get_entity(r.target_id)
            if src and tgt:
                rtype = r.relation_type.value.replace("_", " ").title()
                lines.append(f"| {src.name} | {rtype} | {tgt.name} |")
        lines.append("")

    # Cross-community edges
    external_rels = [
        r
        for r in kg.relations
        if (r.source_id in member_ids) != (r.target_id in member_ids)
        and (r.source_id in member_ids or r.target_id in member_ids)
    ]
    if external_rels:
        lines.append("## Cross-Community Connections")
        lines.append("")
        lines.append("| Source | Relation | Target | Direction |")
        lines.append("|--------|----------|--------|-----------|")
        for r in external_rels[:15]:  # cap to 15 for readability
            src = kg.get_entity(r.source_id)
            tgt = kg.get_entity(r.target_id)
            if src and tgt:
                rtype = r.relation_type.value.replace("_", " ").title()
                direction = "outbound" if r.source_id in member_ids else "inbound"
                lines.append(f"| {src.name} | {rtype} | {tgt.name} | {direction} |")
        lines.append("")

    # Navigation
    lines.append("---")
    lines.append("")
    lines.append("[Back to Index](./index.md) | [Entity Catalog](./entity_catalog.md)")
    lines.append("")

    path = wiki_dir / f"community_{cid}.md"
    path.write_text("\n".join(lines), encoding="utf-8")
    return path


def _write_entity_catalog(wiki_dir: Path, kg: KnowledgeGraph) -> Path:
    """Write a full entity catalog as a single Markdown file."""
    lines: list[str] = []
    lines.append("# Entity Catalog")
    lines.append("")
    lines.append("Complete listing of all extracted entities.")
    lines.append("")

    lines.append("| Entity | Type | Provenance | Confidence | Community | Connections |")
    lines.append("|--------|------|-----------|------------|-----------|-------------|")

    degrees = kg.node_degrees()
    for e in sorted(kg.entities, key=lambda x: degrees.get(x.id, 0), reverse=True):
        etype = e.entity_type.value.replace("_", " ").title()
        cid = kg.communities.get(e.id, "-")
        deg = degrees.get(e.id, 0)
        lines.append(f"| {e.name} | {etype} | {e.provenance} | {e.confidence:.0%} | {cid} | {deg} |")
    lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("[Back to Index](./index.md)")
    lines.append("")

    path = wiki_dir / "entity_catalog.md"
    path.write_text("\n".join(lines), encoding="utf-8")
    return path
